version: "3.9"
services:
  web:
    build: .
    command: ["python", "sync.py"]
    volumes:
      - ./scripts/:/code
      - ./credentials.json:/secrets/credentials.json
    env_file: .localconfig/.env_high_fives